### ISSUE TITLE
Class 1: Introduction to the .NET world

### ISSUE THREAD

**Issue by barahonajm** [MoebiLearning/SoftwareEngineeringIntermediate#1]
Continues improvement is one of the most important points for the courses on Moebi and with your help we will be able to build high quality course more often so, please leave your score for the current class and feel free to leave any feedback.

## Rating Legend

| Mark  | Meaning |
| ------------- | ------------- |
| 👀  | Trainer waiting for your reactions |
| 😕  | Improved Required |
| :smile:   | Meet Expectation  |
| 🚀  | Exceed Expectation  |

## Class Summary
In this first class we have covered the following topics:

- [x] Chapter 00: Understanding why the "concepts are important"
- [x] Chapter 01: Understanding the .NET ecosystem
- [x] Chapter 02: Back to the basics: How the memory really works and more
- [ ] Feedback Collected

**Comment by luisferma** [comment]
Hi Juan! I just notice that the emoticon "smile" is not available in the reactions:

https://developer.github.com/v3/reactions/#reaction-types

I'll put my +1 instead

**Comment by barahonajm** [comment]
> Hi Juan! I just notice that the emoji "blush" is not available in the reactions:
> 
> https://developer.github.com/v3/reactions/#reaction-types
> 
> I'll put my +1 () instead

Thank you for that, I would like to avoid :+1: at least for now, so please whenever you have time try to update it to :smile:

Thank you!

**Comment by wdvf** [comment]
Hi @barahonajm, Veyon is a good way to see your screen, but it would be great if you give us some time to follow your examples on our machines. We spent some time changing the view to our remote machines and sometimes we couldn't follow you.

**Comment by barahonajm** [comment]
Totally agree, I will give more time between exercises as well as to provide the code beforehand in order to address this problem.

Thank you all for your feedback I am closing this ticket and I will soon provide you the next ticket as well as the code of class 2.
